events {
    worker_connections 1024;
}

http {
    upstream api_server {
        server fastapi:8080;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    server {
        listen 80;
        server_name raspberrypi.tail1480d1.ts.net;

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;

        location /health {
            return 200 'healthy';
            add_header Content-Type text/plain;
        }

        location /app/upload {
            client_max_body_size 100M;

            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'https://project.cmi.hr.nl';
                add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'Content-Type';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Length' 0;
                return 204;
            }

            proxy_pass http://api_server;
        }

        location /app/ {
            proxy_pass http://api_server/app/;
        }

        location /docs {
            proxy_pass http://api_server/docs;
        }

        location /redoc {
            proxy_pass http://api_server/redoc;
        }

        location /openapi.json {
            proxy_pass http://api_server/openapi.json;
        }
    }
}
